# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
port: 3000
safe: true

# edit here to achieve your personal greatness
url: lyssascherer.github.io
baseurl: /
title: Lyssa Scherer
author: Lyssa Scherer
description: Personal blog and resume
avatar: foto.jpg
email: lyssa.scherer@gmail.com
github: lyssascherer # username
#twitter: username
linkedin: lyssa-scherer
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: lyssascherer
google_analytics: UA-85962608-2

# needed for travis-ci build
exclude: [vendor]
